# Define two variables in your build pipeline in the web UI:
# dockerId: Your Docker ID for Docker Hub or the admin user name for the Azure Container Registry.
# dockerPassword: Your password for Docker Hub or the admin password for Azure Container Registry.
# Reference
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
# https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker?view=vsts

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'dtcli-webproxy'
  imageNameBuild: 'dtcli-webproxy:$(build.buildId)'
  imageNameLatest: 'dtcli-webproxy:latest'

steps:
- script: |
    sed -i 's#$(dockerId)/$(imageName):.*#image: $(dockerId)/$(imageNameBuild)#' arm/parameters.json
    head -n 20 arm/parameters.json
  displayName: 'Update Docker image'

- script: docker build -t $(dockerId)/$(imageNameBuild) .
  displayName: 'docker build'

- script: |
    docker login -u $(dockerId) -p $(dockerPassword)
    docker push $(dockerId)/$(imageNameBuild)
    docker tag $(dockerId)/$(imageNameBuild) $(dockerId)/$(imageNameLatest)
    docker push $(dockerId)/$(imageNameLatest)
  displayName: 'docker hub push'

- task: CopyFiles@2
  inputs:
    contents: arm/*.json
    targetFolder: $(Build.ArtifactStagingDirectory)

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: $(Build.ArtifactStagingDirectory)
    artifactName: ArmJsonTemplates

